# Generated by Django 4.2.23 on 2025-08-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100, null=True)),
                ('employee_Id', models.CharField(max_length=100, null=True)),
                ('employee_designation', models.CharField(max_length=100, null=True)),
                ('employee_email', models.EmailField(max_length=254)),
                ('employee_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee_salary_date', models.DateField(null=True)),
                ('employee_pf', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
