# Generated by Django 4.2 on 2025-08-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_Id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_designation',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_pf',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_salary',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_salary_date',
        ),
        migrations.AddField(
            model_name='employee',
            name='Allowance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='Basic_pay',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='Deductions',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='Department',
            field=models.CharField(default='HR', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='Designation',
            field=models.CharField(default='Developer', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='HRA',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='Net_salary',
            field=models.DecimalField(decimal_places=2, default=15000.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='Employee_id',
            field=models.CharField(default=1001, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='Employee_name',
            field=models.CharField(default='Unnamed Employee', max_length=100),
            preserve_default=False,
        ),
    ]
