# Generated by Django 4.2 on 2025-08-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_remove_employee_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Department',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Employee_id',
            field=models.IntegerField(),
        ),
    ]
