# Generated by Django 4.2 on 2025-08-04 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_alter_employee_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='HRA',
            new_name='Provident_Fund',
        ),
    ]
