# Generated by Django 4.2 on 2025-08-04 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_rename_hra_employee_provident_fund'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Provident_Fund',
            new_name='employee_pf',
        ),
    ]
